// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    AppLogo: typeof import('./src/components/Application/src/AppLogo.vue')['default']
    Nav: typeof import('./src/components/Nav/Nav.vue')['default']
  }
}

export { }
