// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix']
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AOption: typeof import('@arco-design/web-vue')['Option']
    AppLogo: typeof import('./src/components/Application/src/AppLogo.vue')['default']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    Nav: typeof import('./src/components/Nav/Nav.vue')['default']
  }
}

export { }
